### ISSUE TITLE
Display TV show in addition to episode title

### ISSUE THREAD

**Issue by blackwind** [jvandenbroek/script.afterwatch#2]
In dialogs, I'd like to see the TV show displayed in addition to the episode title. I realize one could argue I should probably know what I just watched, having just watched it, but I often have TV on in the background while I'm doing something in another room, and then I come back to "Delete Episode 149?" Uh... episode 149 of *what*, again? "Delete The Daily Show - Episode 149?" would be much better.

**Comment by jvandenbroek** [comment]
It has been a while ;-) but I've added the show title in the dialog.
