### ISSUE TITLE
Submit to official repository

### ISSUE THREAD

**Issue by blackwind** [jvandenbroek/script.afterwatch#3]
It took me some effort to track down this (what I believe to be essential) add-on. Please consider submitting to the official repository:

http://kodi.wiki/view/Submitting_Add-ons

**Comment by jvandenbroek** [comment]
For now I won't, but you could use this repo instead: https://github.com/jvandenbroek/jvandenbroek-kodi-repo/raw/master/repository.jvandenbroek/repository.jvandenbroek-1.0.1.zip
